server:
  port: 8080

spring:
  datasource:
    name: test---db-demo-spring-boot   #----不是账户名字
    #druid相关配置
    druid:
     #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
       #基本属性
      url: jdbc:mysql://127.0.0.1:3306/db-demo-spring-boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
      username: dongxiang
      password: dongxiang
       #配置初始化大小/最小/最大
      initial-size: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
       #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

# 如果想看到mybatis日志需要做如下配置
logging.level.com.battcn: DEBUG

#TODO 8/9 这里要修改 *mapp.xml 地址、bean的地址；
mybatis:
  mapper-locations: classpath:com/dongxiang/demospringboot04mybatise1/dao/mapping/*.xml
  type-aliases-package: com.dongxiang.demospringboot04mybatise1.dao.entities
  configuration:
  # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
    map-underscore-to-camel-case: true
########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countsql
  reasonable: false
  support-methods-arguments: true
  returnPageInfo: check
#pagehelper.reasonable：分页合理化参数，默认false 时，直接根据参数进行查询。为true时: pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
#support-methods-arguments：支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。






