

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db-demo-spring-boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: dongxiang
    password: dongxiang
  profiles:
    active: dev
#spring.datasource.type
#更多细微的配置可以通过下列前缀进行调整
#spring.datasource.hikari
#spring.datasource.tomcat
#spring.datasource.dbcp2